filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Bob, Welcome to Coot version 0.8.9")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning bob. Welcome to Coot 0.8.9")
set_display_lists_for_maps (0)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
handle_read_draw_molecule_with_recentre ("per5.pdb", 1)
handle_read_draw_molecule_with_recentre ("per1.pdb", 1)
use_graphics_interface_state ()
graphics_molecule_bond_type (0)
graphics_molecule_bond_type (1)
