(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Evening Bob, Welcome to Coot version 0.8.9")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good evening bob. Welcome to Coot 0.8.9")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "1an0_1_8_3.pdb" 1)
(use-graphics-interface-state)
(command-in-path-or-absolute? *probe-command*)
