filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Evening Bob, Welcome to Coot version 0.8.9")
use_graphics_interface_state ()
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good evening bob. Welcome to Coot 0.8.9")
set_display_lists_for_maps (0)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
handle_read_draw_molecule_with_recentre ("1an0_1_8_3.pdb", 1)
use_graphics_interface_state ()
;; # DIRECT SCHEME ((command-in-path-or-absolute? *probe-command*))
