(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Bob, Welcome to Coot version 0.8.9")
(use-graphics-interface-state)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning bob. Welcome to Coot 0.8.9")
(set-display-lists-for-maps 0)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(handle-read-draw-molecule-with-recentre "per5.pdb" 1)
(handle-read-draw-molecule-with-recentre "per1.pdb" 1)
(use-graphics-interface-state)
(graphics-molecule-bond-type 0)
(graphics-molecule-bond-type 1)
